apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-project
  namespace: nju12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-native-project
  template:
    metadata:
      labels:
        app: cloud-native-project
    spec:
      containers:
      - image: harbor.edu.cn/nju12/cloud-native-project:{VERSION}
        name: cloud-native-project