apiVersion: v1
kind: Service
metadata:
  name: cloud-native-homework
  namespace: nju12
spec:
  type: NodePort
  selector:
    app: cloud-native-homework
  ports:
  - nodePort: 40000 # host's port
    port: 8080      # service's port
    targetPort: 8080  # target pod's port