apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-native-homework
  name: cloud-native-homework
  namespace: nju12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-native-homework
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8988"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: cloud-native-homework
    spec:
      containers:
        - image: harbor.edu.cn/nju12/cloud-native-homework:{VERSION}
          name: cloud-native-homework
      imagePullSecrets:
        - name: nju12
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-native-homework
  namespace: nju12
  labels:
    app: cloud-native-homework
spec:
  type: NodePort
  selector:
    app: cloud-native-homework
  ports:
    - name: tcp
      nodePort: 31110
      protocol: TCP
      port: 8080
      targetPort: 8080
